config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="mastr_data/search.html"), name="search"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "imprint/",
        TemplateView.as_view(template_name="pages/imprint.html"),
        name="imprint",
    ),
    path(
        "sources/",
        TemplateView.as_view(template_name="pages/sources.html"),
        name="sources",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("ee_status.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("ee_status.mastr_data.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ee_status/energy_sources/urls.py
from django.urls import path

from .views import current_total_view, monthly_timeline_view

app_name = "energy_sources"
urlpatterns = [
    path("timeline", monthly_timeline_view, name="timeline"),
    path("totals", current_total_view, name="totals"),
]

ee_status/mastr_data/urls.py
from django.urls import path

from .views import (
    multi_polygon_map,
    rankings_view,
    search_municipality,
    search_view,
    totals_view,
)

app_name = "mastr_data"
urlpatterns = [
    path("", search_view, name="search"),
    path("totals", totals_view, name="totals"),
    path("rankings", rankings_view, name="rankings"),
    path("multi_polygon_map/", multi_polygon_map, name="multi_polygon_map"),
]

htmx_urlpatterns = [
    path("search-municipality/", search_municipality, name="search-municipality"),
]

urlpatterns += htmx_urlpatterns

ee_status/users/urls.py
from django.urls import path

from ee_status.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

ee_status/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for EE-Status.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

ee_status/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

ee_status/mastr_data/views.py
import json

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from django.contrib.gis.db.models.functions import AsGeoJSON
from django.core.serializers import serialize
from django.db.models import F, Q, Sum, Window
from django.db.models.functions import Round
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import gettext as _
from plotly.offline import plot

from .filters import CurrentTotalFilter, MonthlyTimelineFilter, RankingsFilter
from .models import CurrentTotal, MonthlyTimeline


def search_municipality(request):
    query = request.POST.get("search")
    # look up all municipalities that contain the text
    # Search logic
    # search for aliases of Germany
    # 0 results = nothing found
    # 1 result = single municipality or a municipality which is a county at the same time ("kreisfreie Stadt")
    # > 1 results:
    #   as many municipalities as the county counts -> county or municipality which contain the name of the county
    #   as many municipalities as the state -> state
    #   more results: return list of results for user

    names_for_germany = [
        "Germany",
        "Deutschland",
        "Bundesrepublik",
        "Schland",
        "alles",
        "BRD",
    ]
    if query in names_for_germany:
        return redirect(reverse("mastr_data:totals"))

    municipality_results = (
        CurrentTotal.objects.filter(
            Q(municipality__icontains=query)
            | Q(municipality_key__icontains=query)
            | Q(zip_code__icontains=query)
        )
        # we exclude municipalities that are their own counties ("kreisfreie Städte")
        # their municipality keys ends with "000"
        .exclude(municipality_key__endswith="000").values(
            "municipality", "county", "state"
        )
    )

    county_results = (
        CurrentTotal.objects.filter(county__icontains=query)
        .values("county", "state")
        # we exclude counties that are their own states ("echte Stadtstaaten": Hamburg, Berlin)
        # their municipality keys ends with "000000"
        .exclude(municipality_key__endswith="000000")
        .exclude(municipality_key="04011000")
        .distinct()
    )
    state_results = (
        CurrentTotal.objects.filter(state__icontains=query).values("state").distinct()
    )

    return render(
        request,
        "mastr_data/partials/search-results.html",
        {
            "municipality_results": municipality_results,
            "county_results": county_results,
            "state_results": state_results,
        },
    )


def multi_polygon_map(request):
    qs = (
        CurrentTotal.objects.filter(geom__isnull=False)
        .annotate(json=AsGeoJSON("geom", precision=4))
        .values("id", "json")
    )

    # Prepare the GeoJSON object
    json_object = json.loads(qs)

    return render(
        request,
        "mastr_data/map_template.html",
        {"geojson": json_object},
    )


def totals_view(request):
    tempdict = request.GET
    municipality_key = tempdict.get("municipality_key")
    municipality = tempdict.get("municipality")
    county = tempdict.get("county")
    state = tempdict.get("state")

    f = MonthlyTimelineFilter(tempdict, queryset=MonthlyTimeline.objects.all())
    data = (
        f.qs.annotate(
            pv_net_sum=Window(
                expression=Sum(F("pv_net_nominal_capacity")), order_by=[F("date").asc()]
            ),
            wind_net_sum=Window(
                expression=Sum(F("wind_net_nominal_capacity")),
                order_by=[F("date").asc()],
            ),
            biomass_net_sum=Window(
                expression=Sum(F("biomass_net_nominal_capacity")),
                order_by=[F("date").asc()],
            ),
            hydro_net_sum=Window(
                expression=Sum(F("hydro_net_nominal_capacity")),
                order_by=[F("date").asc()],
            ),
        )
        .distinct("date")
        .values_list(
            "date", "pv_net_sum", "wind_net_sum", "biomass_net_sum", "hydro_net_sum"
        )
    )

    # transform QuerySet to list
    data = list(data)

    #  Build Graph
    # Extract data for each category (pv, wind, hydro, biomass)
    dates = [item[0] for item in data]
    pv_data = [item[1] if item[1] is not None else 0 for item in data]
    wind_data = [item[2] if item[2] is not None else 0 for item in data]
    hydro_data = [item[3] if item[3] is not None else 0 for item in data]
    biomass_data = [item[4] if item[4] is not None else 0 for item in data]

    # Create traces for each category
    trace_pv = go.Scatter(x=dates, y=pv_data, mode="lines", name=_("Photovoltaics"))
    trace_wind = go.Scatter(x=dates, y=wind_data, mode="lines", name=_("Wind power"))
    trace_hydro = go.Scatter(x=dates, y=hydro_data, mode="lines", name=_("Hydropower"))
    trace_biomass = go.Scatter(
        x=dates,
        y=biomass_data,
        mode="lines",
        name=_("Biomass"),
    )

    # Create the layout for the timeline graph
    layout = go.Layout(
        xaxis=dict(title=_("Date")),
        yaxis=dict(
            title=_("Power generation"),
        ),
        hovermode="x unified",
        template="plotly_white",
    )

    # Create a figure and add traces to it
    fig = go.Figure(
        data=[trace_pv, trace_wind, trace_hydro, trace_biomass], layout=layout
    )

    plt_div = plot(fig, output_type="div", include_plotlyjs=False)

    f_current_totals = CurrentTotalFilter(
        request.GET, queryset=CurrentTotal.objects.all()
    )
    current_object = f_current_totals.qs.first()

    # Determine which realm type we are about to handle
    if municipality or municipality_key:
        realm_type = "municipality"
    elif county:
        realm_type = "county"
    elif state:
        realm_type = "state"
    else:
        realm_type = "country"

    # GET TOTAL NET NOMINAL CAPACITY PER CAPITA
    total_net_nominal_capacity_per_capita = current_object.ratio_and_rank(
        numerator="total_net_nominal_capacity",
        denominator="population",
        realm_type=realm_type,
    )

    # GET TOTAL NET NOMINAL CAPACITY PER SQUARE METERS
    total_net_nominal_capacity_per_area = current_object.ratio_and_rank(
        numerator="total_net_nominal_capacity",
        denominator="area",
        realm_type=realm_type,
    )

    # GET Storage Capacity per capita
    storage_capacity_per_capita = current_object.ratio_and_rank(
        numerator="storage_net_nominal_capacity",
        denominator="population",
        realm_type=realm_type,
    )

    # GET Storage Capacity per are
    storage_capacity_per_area = current_object.ratio_and_rank(
        numerator="storage_net_nominal_capacity",
        denominator="area",
        realm_type=realm_type,
    )

    basics = f_current_totals.qs.aggregate(
        total_population=Sum("population"),
        total_area=Sum("area"),
        total_production_capacity=Sum("total_net_nominal_capacity"),
        total_storage_capacity=Sum("storage_net_nominal_capacity"),
        count_of_devices=Sum("energy_units"),
    )
    basics["realm_type"] = realm_type

    if realm_type == "country":
        basics["realm_name"] = _("Germany")
    else:
        basics["realm_name"] = getattr(current_object, realm_type)

    order = ["municipality", "county", "state"]
    hierarchy = {}
    if realm_type != "country":
        for i in order[order.index(realm_type) : :]:  # noqa: E203
            hierarchy[i] = getattr(current_object, i)
    hierarchy["country"] = _("Germany")

    return render(
        request,
        "mastr_data/totals.html",
        {
            "filter": f_current_totals,
            "total_net_nominal_capacity_per_capita": total_net_nominal_capacity_per_capita,
            "total_net_nominal_capacity_per_area": total_net_nominal_capacity_per_area,
            "storage_capacity_per_capita": storage_capacity_per_capita,
            "storage_capacity_per_area": storage_capacity_per_area,
            "basics": basics,
            "hierarchy": hierarchy,
            "realm_type": realm_type,
            "plt_div": plt_div,
        },
    )


def rankings_view(request):
    tempdict = request.GET
    municipality = tempdict.get("municipality")
    county = tempdict.get("county")
    state = tempdict.get("state")
    numerator = tempdict.get("numerator")
    denominator = tempdict.get("denominator")
    scope = tempdict.get("scope")

    if not numerator and not denominator:
        numerator = "total_net_nominal_capacity"
        denominator = "population"

    f = RankingsFilter(tempdict, queryset=CurrentTotal.objects.all())

    if municipality:
        realm_type = "municipality"
    elif county:
        realm_type = "county"
    elif state:
        realm_type = "state"
    else:
        # when looking at germany, it should still display the different states
        realm_type = "state"

    hierarchy = {}

    if municipality:
        hierarchy["municipality"] = municipality
    if county:
        hierarchy["county"] = county
    if state:
        hierarchy["state"] = state

    hierarchy["country"] = _("Germany")

    basics = {"realm_type": realm_type, "realm_name": next(iter(hierarchy.values()))}

    table_captions = [_("Rank"), realm_type]

    if numerator:
        numerator_annotate = {"numerator": Sum(numerator)}
        table_captions.append(CurrentTotal._meta.get_field(numerator).verbose_name)
        numerator_filter_kwargs = {
            "{}__{}".format(numerator, "isnull"): False,
            "{}__{}".format(numerator, "gt"): 0,
        }
        if denominator:
            denominator_filter_kwargs = {
                "{}__{}".format(denominator, "isnull"): False,
                "{}__{}".format(denominator, "gt"): 0,
            }
            denominator_annotate = {"denominator": Round(Sum(denominator))}
            score_expression = {"score": Sum(numerator) / Sum(denominator)}

ee_status/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

ee_status/templates/mastr_data/map_template.html
{% extends "base.html" %}
{% load i18n static %}
{% load humanize %}

{% load crispy_forms_tags %}
{% block content %}
  <style>
		html, body {
			height: 100%;
			margin: 0;
		}
		.leaflet-container {
			height: 400px;
			width: 600px;
			max-width: 100%;
			max-height: 100%;
		}
	</style>

  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>


  <div id="map" style="height: 500px;"></div>

<script type="text/javascript">
  const map = L.map('map').setView([37.8, 7.4], 4);

  const tiles = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
	  }).addTo(map);

/* global statesData */

  const geojson = L.geoJson({{ geojson|safe }}).addTo(map);

</script>






{% endblock content %}

ee_status/templates/mastr_data/search.html
{% extends "base.html" %}
{% load i18n static %}


{% block content %}
  <div class="px-4 py-5 my-5 text-center">
  <img src="{% static 'images/logo/ee_status_logo_no_text_square.png' %}" alt="Logo" width="250" height="250" class="d-inline-block align-text-center">
    <h1 class="display-5 fw-bold">E<span class="h4">rneuerbare</span> E<span class="h4">nergien</span> S<span
      class="h4">tatus</span></h1>
    <div class="col-lg-9 mx-auto">
      <form autocomplete="off">
        <div class="form-group">

          <input type="text"
                 class="form-control form-control-lg mb-4 search-form"
                 hx-post="{% url 'mastr_data:search-municipality' %}"
                 hx-target='#results'
                 hx-trigger="keyup changed delay:500ms"
                 name="search" id="searchtext"
                 aria-describedby="searchfield"
                 placeholder="{% trans "Search for Municipality, County, State, Zip-Code, Germany..." %}">
        </div>
      </form>
        <div id="results"></div>

    </div>
  </div>

{% endblock content %}

ee_status/templates/mastr_data/timeline.html
{% extends "base.html" %}
{% load i18n %}

{% load crispy_forms_tags %}
{% block content %}
  <form method="get">
    {{ filter.form|crispy }} <input type="hidden"/>
    <button class="btn btn-outline-primary btn-block" type="submit">{% trans "Filter" %}</button>
  </form>

  <h1 class="title">{% trans "Entwicklung Erneuerbare Energien" %}</h1>
  <link href=”http://cdn.pydata.org/bokeh/release/bokeh-2.4.2.min.css" rel=”stylesheet” type=”text/css”>
<link href=”http://cdn.pydata.org/bokeh/release/bokeh-widgets-2.4.2.min.css" rel=”stylesheet” type=”text/css”>

  <script src="https://cdn.bokeh.org/bokeh/release/bokeh-2.4.2.min.js"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.4.2.min.js"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.4.2.min.js"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-api-2.4.2.min.js"></script>

  {{div| safe}}
  {{script| safe}}



{% endblock content %}

ee_status/templates/mastr_data/totals.html
{% extends "base.html" %}
{% load i18n static %}
{% load humanize %}
{% load l10n %}

{% block content %}


  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      {% for realm_type, realm_name in hierarchy.items reversed %}
        {% if not forloop.last %}
          <li class="breadcrumb-item active" aria-current="page">
            <a
              href="{% url 'mastr_data:totals' %}?{{ realm_type }}={{ realm_name }}">{{ realm_name }}</a>
          </li>
        {% else %}
          <li class="breadcrumb-item active" aria-current="page">
            {{ realm_name }}
          </li>
        {% endif %}
      {% endfor %}
    </ol>
  </nav>

  <div class="row mt-1">
    <h1 class="title">{{ basics.realm_name }}</h1>
  </div>
   <div class="row mt-3">
    <ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="#">Overview</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'mastr_data:rankings' %}?numerator=total_net_nominal_capacity&denominator=population
{% for realm_type, realm_name in hierarchy.items %}&{{ realm_type }}={{ realm_name }}{% endfor %}
&scope=">
      Rankings
    </a>
  </li>
</ul>
  </div>

  <div class="row mt-3">
    <script src="{% static 'vendors/plotly/plotly-2.27.0.min.js' %}"></script>
    {{ plt_div|safe }}
  </div>

  <div class="row mt-3">
    <div class="col text-center">
      <h3>{{ basics.total_population|intcomma }}</h3>
      Einwohner:innen
    </div>
    <div class="col text-center">
      <h3>{{ basics.total_area|floatformat:0|intcomma }}</h3>
      km² Fläche
    </div>
    <div class="col text-center">
      <h3>{{ basics.count_of_devices|intcomma }}</h3>erneuerbare Energieanlagen</a>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title text-center">{{ basics.total_production_capacity|floatformat:0|intcomma }} kW</h3>
          <h5 class="card-subtitle mb-2 text-muted text-center">{% trans "Production Capacity" %}</h5>
        </div>
        {% for realm in total_net_nominal_capacity_per_capita %}
          {% if forloop.first %}
            <div class="card-body border-top pb-0">
              <h6>{% trans "Production capacity per capita" %}: {{ realm.score }} kW</h6>
            </div>
          {% else %}
            <div class="row">
              <div class="col-sm-4 ms-4 text-truncate">
                <svg width="1.2em" height="1.2em">
                  <use href="#bi-arrow-return-right"/>
                </svg>
                <a
                  href="{% url 'mastr_data:rankings' %}?{{ basics.realm_type }}={{ basics.realm_name }}&scope={{ realm.realm_type }}&{{ realm.realm_type }}={{ realm.realm_name }}&numerator={{ realm.numerator }}&denominator={{ realm.denominator }}">
                  in {{ realm.realm_name }}</a>
              </div>
              <div class="col text-end">
                {{ realm.rank }}. {% trans "Rank" %}
              </div>
              <div class="col d-none d-md-block">
                <input type="range" class="ranking" min="0" max="{{ realm.total_ranks }}" step="1"
                       value="{{ realm.rank }}"
                       id="customRange{{ forloop.counter }}" disabled>
              </div>
              <div class="col text-start">
                {% trans "of " %} {{ realm.total_ranks }}
              </div>
            </div>
          {% endif %}
        {% endfor %}


        {% for realm in total_net_nominal_capacity_per_area %}
          {% if forloop.first %}
            <div class="card-body border-top pb-0">
              <h6>{% trans "Production capacity per km²" %}: {{ realm.score }} kW</h6>
            </div>
          {% else %}
            <div class="row">
              <div class="col-sm-4 ms-4 text-truncate">
                <svg width="1.2em" height="1.2em">
                  <use href="#bi-arrow-return-right"/>
                </svg>
                <a
                  href="{% url 'mastr_data:rankings' %}?{{ basics.realm_type }}={{ basics.realm_name }}&scope={{ realm.realm_type }}&{{ realm.realm_type }}={{ realm.realm_name }}&numerator={{ realm.numerator }}&denominator={{ realm.denominator }}">
                  in {{ realm.realm_name }}</a>
              </div>
              <div class="col text-end">
                {{ realm.rank }}. {% trans "Rank" %}
              </div>
              <div class="col d-none d-md-block">
                <input type="range" class="ranking" min="0" max="{{ realm.total_ranks }}" step="1"
                       value="{{ realm.rank }}"
                       id="customRange{{ forloop.counter }}" disabled>
              </div>
              <div class="col text-start">
                {% trans "of " %} {{ realm.total_ranks }}
              </div>
            </div>
          {% endif %}
        {% endfor %}

      </div>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title text-center">{{ basics.total_storage_capacity|floatformat:0|intcomma }} kWh</h3>
          <h5 class="card-subtitle mb-2 text-muted text-center">{% trans "Storage Capacity" %}</h5>
        </div>
        {% for realm in storage_capacity_per_capita %}
          {% if forloop.first %}
            <div class="card-body border-top pb-0">
              <h6>{% trans "Storage capacity per capita" %}: {{ realm.score }} kWh</h6>
            </div>
          {% else %}
            <div class="row">
              <div class="col-sm-4 ms-4 text-truncate">
                <svg width="1.2em" height="1.2em">
                  <use href="#bi-arrow-return-right"/>
                </svg>
                <a
                  href="{% url 'mastr_data:rankings' %}?{{ basics.realm_type }}={{ basics.realm_name }}&scope={{ realm.realm_type }}&{{ realm.realm_type }}={{ realm.realm_name }}&numerator={{ realm.numerator }}&denominator={{ realm.denominator }}">
                  in {{ realm.realm_name }}</a>
              </div>
              <div class="col text-end">
                {{ realm.rank }}. {% trans "Rank" %}
              </div>
              <div class="col d-none d-md-block">
                <input type="range" class="ranking" min="0" max="{{ realm.total_ranks }}" step="1"
                       value="{{ realm.rank }}"
                       id="customRange{{ forloop.counter }}" disabled>
              </div>
              <div class="col text-start">
                {% trans "of " %} {{ realm.total_ranks }}
              </div>
            </div>
          {% endif %}
        {% endfor %}


        {% for realm in storage_capacity_per_area %}
          {% if forloop.first %}
            <div class="card-body border-top pb-0">
              <h6>{% trans "Storage capacity per km²" %}: {{ realm.score }} kWh</h6>
            </div>
          {% else %}
            <div class="row">
              <div class="col-sm-4 ms-4 text-truncate">
                <svg width="1.2em" height="1.2em">
                  <use href="#bi-arrow-return-right"/>
                </svg>
                <a
                  href="{% url 'mastr_data:rankings' %}?{{ basics.realm_type }}={{ basics.realm_name }}&scope={{ realm.realm_type }}&{{ realm.realm_type }}={{ realm.realm_name }}&numerator={{ realm.numerator }}&denominator={{ realm.denominator }}">
                  in {{ realm.realm_name }}</a>
              </div>
              <div class="col text-end">
                {{ realm.rank }}. {% trans "Rank" %}
              </div>
              <div class="col d-none d-md-block">
                <input type="range" class="ranking" min="0" max="{{ realm.total_ranks }}" step="1"
                       value="{{ realm.rank }}"
                       id="customRange{{ forloop.counter }}" disabled>
              </div>
              <div class="col text-start">
                {% trans "of " %} {{ realm.total_ranks }}
              </div>
            </div>
          {% endif %}
        {% endfor %}

      </div>
    </div>
  </div>

  <div class="row mb-3">

  </div>

{% endblock content %}