config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="mastr_data/search.html"), name="search"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "imprint/",
        TemplateView.as_view(template_name="pages/imprint.html"),
        name="imprint",
    ),
    path(
        "sources/",
        TemplateView.as_view(template_name="pages/sources.html"),
        name="sources",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("ee_status.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("ee_status.mastr_data.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ee_status/energy_sources/urls.py
from django.urls import path

from .views import current_total_view, monthly_timeline_view

app_name = "energy_sources"
urlpatterns = [
    path("timeline", monthly_timeline_view, name="timeline"),
    path("totals", current_total_view, name="totals"),
]

ee_status/mastr_data/urls.py
from django.urls import path

from .views import (
    multi_polygon_map,
    rankings_view,
    search_municipality,
    search_view,
    totals_view,
)

app_name = "mastr_data"
urlpatterns = [
    path("", search_view, name="search"),
    path("totals", totals_view, name="totals"),
    path("rankings", rankings_view, name="rankings"),
    path("multi_polygon_map/", multi_polygon_map, name="multi_polygon_map"),
]

htmx_urlpatterns = [
    path("search-municipality/", search_municipality, name="search-municipality"),
]

urlpatterns += htmx_urlpatterns

ee_status/users/urls.py
from django.urls import path

from ee_status.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

ee_status/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for EE-Status.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

ee_status/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

ee_status/mastr_data/views.py
import json

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from django.contrib.gis.db.models.functions import AsGeoJSON
from django.core.serializers import serialize
from django.db.models import F, Q, Sum, Window
from django.db.models.functions import Round
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import gettext as _
from plotly.offline import plot

from .filters import CurrentTotalFilter, MonthlyTimelineFilter, RankingsFilter
from .models import CurrentTotal, MonthlyTimeline


def search_municipality(request):
    query = request.POST.get("search")
    # look up all municipalities that contain the text
    # Search logic
    # search for aliases of Germany
    # 0 results = nothing found
    # 1 result = single municipality or a municipality which is a county at the same time ("kreisfreie Stadt")
    # > 1 results:
    #   as many municipalities as the county counts -> county or municipality which contain the name of the county
    #   as many municipalities as the state -> state
    #   more results: return list of results for user

    names_for_germany = [
        "Germany",
        "Deutschland",
        "Bundesrepublik",
        "Schland",
        "alles",
        "BRD",
    ]
    if query in names_for_germany:
        return redirect(reverse("mastr_data:totals"))

    municipality_results = (
        CurrentTotal.objects.filter(
            Q(municipality__icontains=query)
            | Q(municipality_key__icontains=query)
            | Q(zip_code__icontains=query)
        )
        # we exclude municipalities that are their own counties ("kreisfreie Städte")
        # their municipality keys ends with "000"
        .exclude(municipality_key__endswith="000").values(
            "municipality", "county", "state"
        )
    )

    county_results = (
        CurrentTotal.objects.filter(county__icontains=query)
        .values("county", "state")
        # we exclude counties that are their own states ("echte Stadtstaaten": Hamburg, Berlin)
        # their municipality keys ends with "000000"
        .exclude(municipality_key__endswith="000000")
        .exclude(municipality_key="04011000")
        .distinct()
    )
    state_results = (
        CurrentTotal.objects.filter(state__icontains=query).values("state").distinct()
    )

    return render(
        request,
        "mastr_data/partials/search-results.html",
        {
            "municipality_results": municipality_results,
            "county_results": county_results,
            "state_results": state_results,
        },
    )


def multi_polygon_map(request):
    qs = (
        CurrentTotal.objects.filter(geom__isnull=False)
        .annotate(json=AsGeoJSON("geom", precision=4))
        .values("id", "json")
    )

    # Prepare the GeoJSON object
    json_object = json.loads(qs)

    return render(
        request,
        "mastr_data/map_template.html",
        {"geojson": json_object},
    )


def totals_view(request):
    tempdict = request.GET
    municipality_key = tempdict.get("municipality_key")
    municipality = tempdict.get("municipality")
    county = tempdict.get("county")
    state = tempdict.get("state")

    f = MonthlyTimelineFilter(tempdict, queryset=MonthlyTimeline.objects.all())
    data = (
        f.qs.annotate(
            pv_net_sum=Window(
                expression=Sum(F("pv_net_nominal_capacity")), order_by=[F("date").asc()]
            ),
            wind_net_sum=Window(
                expression=Sum(F("wind_net_nominal_capacity")),
                order_by=[F("date").asc()],
            ),
            biomass_net_sum=Window(
                expression=Sum(F("biomass_net_nominal_capacity")),
                order_by=[F("date").asc()],
            ),
            hydro_net_sum=Window(
                expression=Sum(F("hydro_net_nominal_capacity")),
                order_by=[F("date").asc()],
            ),
        )
        .distinct("date")
        .values_list(
            "date", "pv_net_sum", "wind_net_sum", "biomass_net_sum", "hydro_net_sum"
        )
    )

    # transform QuerySet to list
    data = list(data)

    #  Build Graph
    # Extract data for each category (pv, wind, hydro, biomass)
    dates = [item[0] for item in data]
    pv_data = [item[1] if item[1] is not None else 0 for item in data]
    wind_data = [item[2] if item[2] is not None else 0 for item in data]
    hydro_data = [item[3] if item[3] is not None else 0 for item in data]
    biomass_data = [item[4] if item[4] is not None else 0 for item in data]

    # Create traces for each category
    trace_pv = go.Scatter(x=dates, y=pv_data, mode="lines", name=_("Photovoltaics"))
    trace_wind = go.Scatter(x=dates, y=wind_data, mode="lines", name=_("Wind power"))
    trace_hydro = go.Scatter(x=dates, y=hydro_data, mode="lines", name=_("Hydropower"))
    trace_biomass = go.Scatter(
        x=dates,
        y=biomass_data,
        mode="lines",
        name=_("Biomass"),
    )

    # Create the layout for the timeline graph
    layout = go.Layout(
        xaxis=dict(title=_("Date")),
        yaxis=dict(
            title=_("Power generation"),
        ),
        hovermode="x unified",
        template="plotly_white",
    )

    # Create a figure and add traces to it
    fig = go.Figure(
        data=[trace_pv, trace_wind, trace_hydro, trace_biomass], layout=layout
    )

    plt_div = plot(fig, output_type="div", include_plotlyjs=False)

    f_current_totals = CurrentTotalFilter(
        request.GET, queryset=CurrentTotal.objects.all()
    )
    current_object = f_current_totals.qs.first()

    # Determine which realm type we are about to handle
    if municipality or municipality_key:
        realm_type = "municipality"
    elif county:
        realm_type = "county"
    elif state:
        realm_type = "state"
    else:
        realm_type = "country"

    # GET TOTAL NET NOMINAL CAPACITY PER CAPITA
    total_net_nominal_capacity_per_capita = current_object.ratio_and_rank(
        numerator="total_net_nominal_capacity",
        denominator="population",
        realm_type=realm_type,
    )

    # GET TOTAL NET NOMINAL CAPACITY PER SQUARE METERS
    total_net_nominal_capacity_per_area = current_object.ratio_and_rank(
        numerator="total_net_nominal_capacity",
        denominator="area",
        realm_type=realm_type,
    )

    # GET Storage Capacity per capita
    storage_capacity_per_capita = current_object.ratio_and_rank(
        numerator="storage_net_nominal_capacity",
        denominator="population",
        realm_type=realm_type,
    )

    # GET Storage Capacity per are
    storage_capacity_per_area = current_object.ratio_and_rank(
        numerator="storage_net_nominal_capacity",
        denominator="area",
        realm_type=realm_type,
    )

    basics = f_current_totals.qs.aggregate(
        total_population=Sum("population"),
        total_area=Sum("area"),
        total_production_capacity=Sum("total_net_nominal_capacity"),
        total_storage_capacity=Sum("storage_net_nominal_capacity"),
        count_of_devices=Sum("energy_units"),
    )
    basics["realm_type"] = realm_type

    if realm_type == "country":
        basics["realm_name"] = _("Germany")
    else:
        basics["realm_name"] = getattr(current_object, realm_type)

    order = ["municipality", "county", "state"]
    hierarchy = {}
    if realm_type != "country":
        for i in order[order.index(realm_type) : :]:  # noqa: E203
            hierarchy[i] = getattr(current_object, i)
    hierarchy["country"] = _("Germany")

    return render(
        request,
        "mastr_data/totals.html",
        {
            "filter": f_current_totals,
            "total_net_nominal_capacity_per_capita": total_net_nominal_capacity_per_capita,
            "total_net_nominal_capacity_per_area": total_net_nominal_capacity_per_area,
            "storage_capacity_per_capita": storage_capacity_per_capita,
            "storage_capacity_per_area": storage_capacity_per_area,
            "basics": basics,
            "hierarchy": hierarchy,
            "realm_type": realm_type,
            "plt_div": plt_div,
        },
    )


def rankings_view(request):
    tempdict = request.GET
    municipality = tempdict.get("municipality")
    county = tempdict.get("county")
    state = tempdict.get("state")
    numerator = tempdict.get("numerator")
    denominator = tempdict.get("denominator")
    scope = tempdict.get("scope")

    if not numerator and not denominator:
        numerator = "total_net_nominal_capacity"
        denominator = "population"

    f = RankingsFilter(tempdict, queryset=CurrentTotal.objects.all())

    if municipality:
        realm_type = "municipality"
    elif county:
        realm_type = "county"
    elif state:
        realm_type = "state"
    else:
        # when looking at germany, it should still display the different states
        realm_type = "state"

    hierarchy = {}

    if municipality:
        hierarchy["municipality"] = municipality
    if county:
        hierarchy["county"] = county
    if state:
        hierarchy["state"] = state

    hierarchy["country"] = _("Germany")

    basics = {"realm_type": realm_type, "realm_name": next(iter(hierarchy.values()))}

    table_captions = [_("Rank"), realm_type]

    if numerator:
        numerator_annotate = {"numerator": Sum(numerator)}
        table_captions.append(CurrentTotal._meta.get_field(numerator).verbose_name)
        numerator_filter_kwargs = {
            "{}__{}".format(numerator, "isnull"): False,
            "{}__{}".format(numerator, "gt"): 0,
        }
        if denominator:
            denominator_filter_kwargs = {
                "{}__{}".format(denominator, "isnull"): False,
                "{}__{}".format(denominator, "gt"): 0,
            }
            denominator_annotate = {"denominator": Round(Sum(denominator))}
            score_expression = {"score": Sum(numerator) / Sum(denominator)}

ee_status/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

ee_status/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}EE-Status{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Displaying Data from the 'Marktstammdatenregister'.">
  <meta name="author" content="Finn Hees">

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

  {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
  {% endblock %}
  <!-- Le javascript
  ================================================== -->
  {# Placed at the top of the document so pages load faster with defer #}
  {% block javascript %}
    <!-- Bootstrap JS -->
    <script defer src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Your stuff: Third-party javascript libraries go here -->

    <!-- place project specific Javascript in this file -->
    <script defer src="{% static 'js/project.js' %}"></script>
    <!-- HTMX -->
        <script defer src="{% static 'vendors/htmx/htmx_1.9.10.min.js.js' %}"></script>

  {% endblock javascript %}

</head>

<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

<div class="mb-1">
  <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'mastr_data:search' %}">
              <img src="{% static 'images/logo/ee_status_logo_no_text_square.png' %}" alt="Logo" width="50" height="50" class="d-inline-block align-text-center"> EE-Status</a>
      {% if request.resolver_match.url_name != 'search' %}

      {% endif %}
      <button class="navbar-toggler navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </nav>

</div>



{% if messages %}
  {% for message in messages %}
    <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endfor %}
{% endif %}

<div class="container mt-3 pb-5">
  {% block content %}


  {% endblock content %}
</div>

<div class="fixed-bottom bg-light border-top">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-1 ms-4 me-4">
    <p class="col-md-6 mb-0 text-muted">© 2023 EE-Status</p>


    <ul class="nav col-md-6 justify-content-end">
      <li class="nav-item"><a href="{% url 'imprint' %}"
                              class="nav-link px-2 text-muted">{% trans "Imprint and data policy" %}</a></li>
      <li class="nav-item"><a href="{% url 'sources' %}" class="nav-link px-2 text-muted">{% trans "Sources" %}</a></li>
      <li class="nav-item"><a href="{% url 'about' %}" class="nav-link px-2 text-muted">{% trans "About us" %}</a></li>
    </ul>
  </footer>
</div>


<!-- /container -->

{% block modal %}{% endblock modal %}

{% block inline_javascript %}
  {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */
      });
    </script>
  {% endcomment %}
  <script src="{% static 'js/external/sorttable.js' %}"></script>
{% endblock inline_javascript %}
<!-- SVG Icons
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!-- Learn about this on: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use -->
{% block icons %}
  <div class="d-none">
    {% include "icons.html" %}
  </div>
{% endblock icons %}

<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function () {
    var u = "https://analytics.interaction.digital/";
    _paq.push(['setTrackerUrl', u + 'matomo.php']);
    _paq.push(['setSiteId', '21']);
    var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
    g.async = true;
    g.src = u + 'matomo.js';
    s.parentNode.insertBefore(g, s);
  })();
</script>
<!-- End Matomo Code -->

</body>
</html>